[package]
name = "eth-sparse-mpt"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
eyre = "0.6.12"
hash-db = "0.15.2"
thiserror = "1.0.61"
triehash = "0.8.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
proptest = "1.5.0"


alloy-trie = { git = "https://github.com/alloy-rs/trie", rev = "f530dfa22a0233968483ebeefb6c1d73f370456b"}

reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-db-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-db-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-errors = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-libmdbx = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-trie = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-trie-parallel = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3", features = ["test-utils"] }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }

# version is copied from reth  "v1.0.3" dependencies
revm = { version = "12.1.0", features = [
    "std",
    "secp256k1",
    "optional_balance_check",
], default-features = false }
revm-primitives = { version = "7.1.0", features = [
    "std",
], default-features = false }
revm-inspectors = "0.5"

ethereum_ssz_derive = "0.5"
ethereum_ssz = "0.5"

alloy-primitives = "0.7.2"
alloy-rlp = "0.3.4"
alloy-chains = "0.1.23"
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032", features = ["ipc", "pubsub"] }
alloy-pubsub = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }
alloy-eips = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }
alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }
alloy-network = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }
alloy-node-bindings = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }
alloy-consensus = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032", features = ["kzg"] }
alloy-serde = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }
alloy-rpc-types-beacon = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032", features = [
    "ssz",
] }
alloy-rpc-types-engine = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032", features = [
    "ssz",
] }
alloy-rpc-types-eth = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }
alloy-signer-local = { git = "https://github.com/alloy-rs/alloy", rev = "f2d80032" }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "trie_insert_bench"
harness = false