[package]
name = "eth-sparse-mpt"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
alloy-trie = "0.4.1"
eyre = "0.6.12"
hash-db = "0.15.2"
thiserror = "1.0.61"
triehash = "0.8.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
proptest = "1.4.0"


reth = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.6" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.6" }
reth-interfaces = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.6" }
#reth-libmdbx = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.6" }
#reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.6" }
#reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.6" }
reth-trie = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.6" }
#reth-trie-parallel = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.6" }
#reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.6" }

# version is copied from reth  "v0.2.0-beta.6" dependencies
#revm = { version = "8.0.0", features = ["std", "secp256k1", "optional_balance_check"], default-features = false }
#revm-primitives = { version = "3.1.0", features = ["std", ], default-features = false }
#revm-inspectors = { git = "https://github.com/paradigmxyz/evm-inspectors", rev = "dc614ee" }

alloy-primitives = { version = "0.7.0", features = ["asm-keccak", "serde"] }
alloy-rlp = "0.3.4"
dashmap = "5.5.3"
#alloy-chains = { version = "0.1.15", feature = ["serde", "rlp", "arbitrary"] }
#alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "39b8695" }
#alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "39b8695" }
#alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy", rev = "39b8695" }
#alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "39b8695" }
#alloy-network = { git = "https://github.com/alloy-rs/alloy", rev = "39b8695" }
#alloy-transport = { git = "https://github.com/alloy-rs/alloy", rev = "39b8695" }
#alloy-trie = { git = "https://github.com/alloy-rs/alloy", rev = "39b8695" }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "trie_insert_bench"
harness = false
